version: '2'
services:
  elasticsearch_primary_master:
    #image: vaclavadamec/docker-composer-market:elasticsearch
    build: elasticsearch/
    command: elasticsearch -Dscript.search=on -Dscript.groovy.sandbox.enabled=true -Dscript.engine.groovy.inline.aggs=on -Des.network.host=172.22.0.10 -Dnode.data=false -Dnode.master=true -Ddiscovery.zen.ping.multicast.enabled=false -Ddiscovery.zen.ping.unicast.hosts="172.22.0.11"
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
        app_net:
          ipv4_address: 172.22.0.10
    logging:
      driver: fluentd
      options:
        fluentd-address: "172.22.0.23:24224"
        tag: "docker.elkmaster"

  elasticsearch_secondary_master:
    #image: vaclavadamec/docker-composer-market:elasticsearch
    build: elasticsearch/
    command: elasticsearch -Dscript.search=on -Dscript.groovy.sandbox.enabled=true -Dscript.engine.groovy.inline.aggs=on -Des.network.host=172.22.0.11 -Dnode.data=false -Dnode.master=true -Ddiscovery.zen.ping.multicast.enabled=false -Ddiscovery.zen.ping.unicast.hosts="172.22.0.10"
    ports:
      - "9201:9200"
      - "9301:9300"
    links:
      - elasticsearch_primary
    depends_on:
      - elasticsearch_primary
    networks:
        app_net:
          ipv4_address: 172.22.0.11
    logging:
      driver: fluentd
      options:
        fluentd-address: "172.22.0.23:24224"
        tag: "docker.elkmaster"

  elasticsearch_primary:
    #image: vaclavadamec/docker-composer-market:elasticsearch
    build: elasticsearch/
    command: elasticsearch -Dscript.search=on -Dscript.groovy.sandbox.enabled=true -Dscript.engine.groovy.inline.aggs=on -Des.network.host=172.22.0.12 -Dnode.data=true -Dnode.master=false -Ddiscovery.zen.ping.multicast.enabled=false -Ddiscovery.zen.ping.unicast.hosts="172.22.0.10,172.22.0.11"
    ports:
      - "9202:9200"
      - "9302:9300"
    networks:
        app_net:
          ipv4_address: 172.22.0.12
    logging:
      driver: fluentd
      options:
        fluentd-address: "172.22.0.23:24224"
        tag: "docker.elkmaster"

  elasticsearch_secondary:
    #image: vaclavadamec/docker-composer-market:elasticsearch
    build: elasticsearch/
    command: elasticsearch -Dscript.search=on -Dscript.groovy.sandbox.enabled=true -Dscript.engine.groovy.inline.aggs=on -Des.network.host=172.22.0.13 -Dnode.data=true -Dnode.master=false -Ddiscovery.zen.ping.multicast.enabled=false -Ddiscovery.zen.ping.unicast.hosts="172.22.0.10,172.22.0.11"
    ports:
      - "9203:9200"
      - "9303:9300"
    links:
      - elasticsearch_primary
    depends_on:
      - elasticsearch_primary
    networks:
        app_net:
          ipv4_address: 172.22.0.13
    logging:
      driver: fluentd
      options:
        fluentd-address: "172.22.0.23:24224"
        tag: "docker.elkmaster"

  elasticsearch_tertiary:
    #image: vaclavadamec/docker-composer-market:elasticsearch
    build: elasticsearch/
    command: elasticsearch -Dscript.search=on -Dscript.groovy.sandbox.enabled=true -Dscript.engine.groovy.inline.aggs=on -Des.network.host=172.22.0.14 -Dnode.data=true -Dnode.master=false -Ddiscovery.zen.ping.multicast.enabled=false -Ddiscovery.zen.ping.unicast.hosts="172.22.0.10,172.22.0.11"
    ports:
      - "9204:9200"
      - "9304:9300"
    links:
      - elasticsearch_primary
    depends_on:
      - elasticsearch_primary
    networks:
        app_net:
          ipv4_address: 172.22.0.14
    logging:
      driver: fluentd
      options:
        fluentd-address: "172.22.0.23:24224"
        tag: "docker.elkmaster"

  elasticsearch_gateway:
    #image: vaclavadamec/docker-composer-market:elasticsearch
    build: elasticsearch/
    command: elasticsearch -Dscript.search=on -Dscript.groovy.sandbox.enabled=true -Dscript.engine.groovy.inline.aggs=on -Des.network.host=172.22.0.20 -Dnode.data=false -Dnode.master=false -Ddiscovery.zen.ping.multicast.enabled=false -Ddiscovery.zen.ping.unicast.hosts="172.22.0.10,172.22.0.11"
    ports:
      - "9210:9200"
      - "9310:9300"
    links:
      - elasticsearch_primary
    depends_on:
      - elasticsearch_primary
    networks:
        app_net:
          ipv4_address: 172.22.0.20
    logging:
      driver: fluentd
      options:
        fluentd-address: "172.22.0.23:24224"
        tag: "docker.elkmaster"

  logstash:
    #image: vaclavadamec/docker-composer-market:logstash
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
      - ./logstash/templates:/etc/logstash/templates
    ports:
      - "5000:5000"
      - "5001:5001"
    links:
      - elasticsearch_primary
    depends_on:
      - elasticsearch_primary
    networks:
        app_net:
          ipv4_address: 172.22.0.21
    logging:
      driver: fluentd
      options:
        fluentd-address: "172.22.0.23:24224"
        tag: "docker.elkmaster"

  kibana:
    #image: vaclavadamec/docker-composer-market:kibana
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch_primary
    depends_on:
      - elasticsearch_primary
    networks:
        app_net:
          ipv4_address: 172.22.0.22
    logging:
      driver: fluentd
      options:
        fluentd-address: "172.22.0.23:24224"
        tag: "docker.elkmaster"

  fluentd:
    #image: vaclavadamec/docker-composer-market:fluentd
    build: fluentd/
    ports:
      - "24224:5140"
    links:
      - elasticsearch_primary
    depends_on:
      - elasticsearch_primary
    networks:
        app_net:
          ipv4_address: 172.22.0.23

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
      - subnet: 172.22.0.0/24
        gateway: 172.22.0.1
